{
  "openapi": "3.0.0",
  "info": {
    "title": "Empathetic Response Generator API",
    "version": "1.0.0",
    "description": "API for generating empathetic and ethically safe responses to user messages."
  },
  "paths": {
    "/generate_response": {
      "post": {
        "summary": "Generate an empathetic response",
        "operationId": "generateEmpatheticResponse",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_message": {
                    "type": "string",
                    "description": "The user's most recent message."
                  },
                  "conversation_context": {
                    "type": "string",
                    "description": "Summary of prior chat messages or mood."
                  }
                },
                "required": ["user_message"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful empathetic response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "reply_text": {
                      "type": "string",
                      "description": "Generated empathetic message for the user."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
